---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: migration-agent
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: migration-agent
rules:
  - apiGroups:
    - "*"
    resources:
    - "*"
    verbs:
    - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: migration-agent
subjects:
- kind: ServiceAccount
  name: migration-agent
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: migration-agent
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: migration-agent
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: migration-agent
  template:
    metadata:
      labels:
        name: migration-agent
    spec:
      hostNetwork: true
      hostPID: true
      serviceAccountName: migration-agent
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      containers:
      - name: migration-agent
        image: husseingalal/migration-agent:dev
        imagePullPolicy: Always
        securityContext:
          privileged: true
        command:
          - "sh"
          - "-c"
          - "migration-agent --s3-region us-west-2 --s3-bucket <bucket-name> --s3-folder <folder> --s3-access-key <access-key> --s3-secret-key <secret-key> --snapshot <snapshot-name> && sleep 9223372036854775807"
        volumeMounts:
        - name: varlibrancher
          mountPath: /var/lib/rancher
        - name: etcssl
          mountPath: /etc/kubernetes/ssl
        - name: etcrancher
          mountPath: /etc/rancher
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlibrancher
        hostPath:
          path: /var/lib/rancher
      - name: etcssl
        hostPath:
          path: /etc/kubernetes/ssl
      - name: etcrancher
        hostPath:
          path: /etc/rancher
